# Generated by Django 5.2.6 on 2025-09-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hotel.hotel')),
            ],
        ),
    ]
