# Generated by Django 5.2.6 on 2025-09-22 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('hotel', '0001_initial'),
        ('persona', '0002_rename_docuemento_identidad_persona_documento_identidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('hora_trabajo', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='cargo.cargo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='hotel.hotel')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('persona.persona',),
        ),
    ]
