# Generated by Django 5.2.6 on 2025-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='docuemento_identidad',
            new_name='documento_identidad',
        ),
    ]
