# Generated by Django 5.2.6 on 2025-09-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('vip', models.BooleanField(default=False)),
            ],
            bases=('persona.persona',),
        ),
    ]
